# render.yaml
services:
  - type: web
    name: lifttracker-ai
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
