[package]
name = "lift-legends"
version = "0.1.0"
description = "Lift Legends Desktop"
authors = ["You"]
edition = "2021"

[build-dependencies]
tauri-build = "2"

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
