name: Generate assets from logo

on:
  push:
    branches: [ main ]
    paths:
      - 'public/branding/logo.png'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Generate icons and screenshots
        run: |
          npm run assets:from-logo

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain public/icons public/screenshots)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/icons public/screenshots
            git commit -m "chore(assets): re-generate icons/screenshots from logo"
            git push
          else
            echo "No asset changes to commit."
          fi

