name: ci-build
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  guard-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Guard: no dist/ tracked
        run: |
          if git ls-files -- 'dist/*' | grep -q .; then
            echo "ERROR: dist/ contains tracked files. Remove them and keep dist/ in .gitignore."
            exit 1
          fi
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build

