name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GROQ_MODEL: llama-3.1-8b-instant
      PORT: 8080
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Test (optional)
        run: npm test --if-present

      - name: Build TypeScript
        run: npm run build --if-present

      - name: Smoke run (compiled server)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          node dist/LiftTrackerAI/server/index.js &
          sleep 3
          curl -sS -X POST http://localhost:8080/api/coach \
            -H "Content-Type: application/json" \
            -d '{"messages":[{"role":"user","content":"Say ok."}]}' \
            | tee /tmp/coach.json
          pkill -f "dist/LiftTrackerAI/server/index.js" || true
