name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run check
      - run: npm test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E
        env:
          E2E_BASE_URL: http://localhost:5173
        run: npm run test:e2e
      - name: Verify repo state
        run: node scripts/verify.mjs
      - if: github.event_name == 'push'
        uses: amondnet/vercel-action@v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
