name: Release

on:
  push:
    tags:
      - "*"

jobs:
  desktop:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - uses: dtolnay/rust-toolchain@stable
      - run: npm ci
      - run: npx tauri build --config apps/desktop/src-tauri/tauri.conf.json
      - uses: softprops/action-gh-release@v2
        with:
          files: apps/desktop/src-tauri/target/release/bundle/**

  android:
    needs: desktop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - run: npm ci
      - run: npm run build
      - run: npx cap sync android
        working-directory: apps/mobile
      - run: ./gradlew assembleRelease bundleRelease
        working-directory: apps/mobile/android
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            apps/mobile/android/app/build/outputs/apk/release/*.apk
            apps/mobile/android/app/build/outputs/bundle/release/*.aab

  ios:
    needs: desktop
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npx cap sync ios
        working-directory: apps/mobile
      - run: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive archive
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build
        working-directory: apps/mobile/ios
      - uses: softprops/action-gh-release@v2
        with:
          files: apps/mobile/ios/build/*.ipa
